import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Delius, Exo_2, Noto_Sans, Playfair_Display } from "next/font/google";
import { CartProvider } from "./Components/cart/CartContext";
import "./globals.css";
import { cn } from "@/lib/utils";

const playfairDisplayHeading = Playfair_Display({subsets:['latin'],variable:'--font-heading'});

const notoSans = Noto_Sans({subsets:['latin'],variable:'--font-sans'});

const exo = Exo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable:"--font-Logo"
})
const myFont = Delius({
  subsets: ["latin"],
  weight: "400",
  variable:"--font-delius"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("font-sans", notoSans.variable, playfairDisplayHeading.variable)}>
      <body className={exo.className}>
        <CartProvider>
          <Toaster />
          {children}
        </CartProvider>
        </body>
    </html>
  );
}
