import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Delius, Exo_2 } from "next/font/google";
import { CartProvider } from "./Components/cart/CartContext";
import "./globals.css";

const exo = Exo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable:"--font-Logo"
})
const myFont = Delius({
  subsets: ["latin"],
  weight: "400",
  variable:"--font-delius"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <CartProvider>
          <Toaster />
          {children}
        </CartProvider>
        </body>
    </html>
  );
}
